version: '3.9'

services:
  backend:
    build: .
    volumes:
      - '.:/usr/src/app/'
    working_dir: /usr/src/app/
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - '8080:8080'
#    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8080']
  postgres:
    image: postgres
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

networks:
  backend: